### ISSUE TITLE
Stock install should support newer version of elastic search

### ISSUE THREAD

**Issue by j3p0uk** [StackStorm-Exchange/stackstorm-elasticsearch#5]
New install kept returning issues with my elastic search 5.5.0 installation.  Modifying version check appears to enable it to work with no other changes (modded to accept up to 5.6.0)

**Comment by LindsayHill** [comment]
That's probably OK for a short-term workaround. But it looks like what we really need to do here is update the underlying libraries, which includes a fair bit more work. See https://github.com/StackStorm/st2contrib/issues/558 (old location for this repo).
