### ISSUE TITLE
Get required parameters from configuration file

### ISSUE THREAD

**Issue by jaf-jaf** [StackStorm-Exchange/stackstorm-elasticsearch#7]
Hi, should be possible to use host parameter value, set in /opt/stackstorm/configs/elaticsearch.yaml file, in order to avoid pass it in elasticsearch.search.body invocation?
I would like to establish my host by configuration and avoid to pass host parameter in search action, but when I do that I get: 
ERROR: 400 Client Error: Bad Request
MESSAGE: 'host' is a required property for url: http://127.0.0.1:9101/v1/executions

**Comment by LindsayHill** [comment]
You're right, this does seem a bit messed up when looking at the code. I'll have to spend a bit of time looking through it trying to figure out how to unwind this. I think it is partly related to the auto-generation of actions. As a short-term workaround, you could change your `config.schema.yaml`, and set a default value for the `host` parameter.

**Comment by jaf-jaf** [comment]
Ok, thank you very much for confirmation and for the workaround.
